apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-server
    spec:
      containers:
      - image: spring6authserver:0.0.1-SNAPSHOT
        name: spring6authserver
        resources: {}
status: {}
